Ecomerce_Restaurant/Ecomerce_Restaurant/Controllers/FoodModelController/FoodNamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ecomerce_Restaurant.Models.FoodModels;
using System.IO;

namespace Ecomerce_Restaurant.Controllers.FoodModelController
{
    public class FoodNamesController : Controller
    {
        public RestaurantContext db = new RestaurantContext();

        // GET: FoodNames
        public ActionResult Index()
        {
            return View(db.Foods.ToList());
        }

        // GET: FoodNames/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food foodName = db.Foods.Find(id);
            if (foodName == null)
            {
                return HttpNotFound();
            }
            return View(foodName);
        }

		//// GET: FoodNames/Create
		//public ActionResult Create()
		//{
		//	var v = db.FoodCategoriesesTable.Select(r => r.CategoryName).Distinct();
		//	ViewBag.CategoryNames = v;
		//   return PartialView();
		//}

		//// POST: FoodNames/Create
		//// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		//// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public ActionResult Create(FoodName foodName, HttpPostedFileBase foodpic)
		//{
		//	foodName.FoodItemPicName = foodName.Name + ".png";
		//	if (ModelState.IsValid)
		//	{
		//		if (foodpic != null && foodpic.ContentLength > 0)
		//		{
		//			var filename = Path.GetFileName(foodpic.FileName);
		//			string x1 = foodName.Name;
		//			string newfilename = x1 + ".png";
		//			var filePath1 = Path.Combine(Server.MapPath("~/Images"), newfilename);
		//			foodpic.SaveAs(filePath1);
		//			db.FoodNamesTable.Add(foodName);
		//			db.SaveChanges();
		//		}
		//		else {
		//			foodName.FoodItemPicName = "default.png";
		//			db.FoodNamesTable.Add(foodName);
		//			db.SaveChanges();
		//		}
		//		return RedirectToAction("Index");
		//	}
		//	else
		//	{
		//		var v = db.FoodCategoriesesTable.Select(r => r.CategoryName).Distinct();
		//		ViewBag.CategoryNames = v;
		//		return View(foodName);
		//	}

		//}

        // GET: FoodNames/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food foodName = db.Foods.Find(id);

            var c= db.FoodCategories.Select(r => r.CategoryName).ToList();
            
            return PartialView(foodName);
        }



        // POST: FoodNames/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Food foodName, string oldpicname, HttpPostedFileBase foodpic)
        {
            foodName.FoodImageName = foodName.Name + ".png";


            if (ModelState.IsValid)
            {

                if (foodpic != null && foodpic.ContentLength > 0)
                {
                    string x1 = foodName.Name;
                    string newfilename = x1 + ".png";
                    var filePath1 = Path.Combine(Server.MapPath("~/Images"), newfilename);
                    foodpic.SaveAs(filePath1);
                    db.Entry(foodName).State = EntityState.Modified;
                    db.SaveChanges(); var filename = Path.GetFileName(foodpic.FileName);
                }
                else
                {
                    if (!string.IsNullOrEmpty(oldpicname))
                    {
                        foodName.FoodImageName = oldpicname;
                    }
                    else
                    {
                        foodName.FoodImageName = "default.png";
                    }
                    db.Entry(foodName).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index", "FoodCategories");

            }
            var c = db.FoodCategories.Select(r => r.CategoryName).ToList();
            return View(foodName);
        }

        // GET: FoodNames/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Food foodName = db.Foods.Find(id);
            if (foodName == null)
            {
                return HttpNotFound();
            }
            return PartialView(foodName);
        }

        // POST: FoodNames/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Food foodName = db.Foods.Find(id);
            db.Foods.Remove(foodName);
            db.SaveChanges();
            return RedirectToAction("Index", "FoodCategories");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Ecomerce_Restaurant/Ecomerce_Restaurant/Controllers/HomeController.cs
using Ecomerce_Restaurant.Models.FoodModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ecomerce_Restaurant.Controllers
{
    public class HomeController : Controller
    {

        RestaurantContext db = new RestaurantContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        [HttpPost]
        public ActionResult SearchView(string searchvalue)
        {

            var v = db.Foods.Where(r => r.CategoryName.Contains(searchvalue)).ToList();
            return View(v);
        }

        public ActionResult AdminView() 
        {

            var v = db.Foods.OrderBy(r => r.CategoryName).ToList(); 
            return View(v);
        }
    

    }
}

Ecomerce_Restaurant/Ecomerce_Restaurant/Views/Home/AdminView.cshtml
@model IEnumerable<Ecomerce_Restaurant.Models.FoodModels.FoodName>


<div class="panel panel-default">
    <div class="panel-heading">
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CategoryName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodDescription)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodPrice)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodRating)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TotalRatedPeople)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodItemPicName)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr class="warning">
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodDescription)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodRating)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalRatedPeople)
                        </td>
                        <td>
                            <img src="~/Images/@(item.FoodItemPicName)" height="50" width="50" />

                        </td>
                        <td>
                            <p class="button">
                                @Html.ActionLink("Add to cart", "AddToCart","CustomerOrders", new { id = item.ID }, "")
                            </p>

                        </td>
                        @*<td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                            </td>*@
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

Ecomerce_Restaurant/Ecomerce_Restaurant/Views/Home/Contact.cshtml
@{
	ViewBag.Title = "Contact";
}
@section chat{

	<!--Script references. -->
	<!--Reference the jQuery library. -->
	<script src="~/Scripts/jquery-3.1.1.min.js"></script>
	<!--Reference the SignalR library. -->
	<script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
	<script src="~/signalr/hubs"></script>
	<script src="~/Scripts/chatScript.js"></script>

}
<div class="container">
	<div class="row pull-left">
		<div class="col-xs-4">
			<div class="container">
				<div class="span4">
					<h2>Find Us</h2>
					<address>
						<strong>Dhaka Food Restaurant & Bar</strong><br>
						49 Hanstavagen<br>
						162 64<br>
						Kista<br>
						Sweden<br>
						<abbr title="Phone">P:</abbr> +460700000000
					</address>
				</div>
			</div>
		</div>
		<div class="col-xs-4">
			<div>
				<div id="googleMap" style="width: 300px; height: 300px"></div>
			</div>
		</div>
		<div class="col-xs-4">
			<div>
				<div class="pull-left">
					<div class="form-group">
						<span>
							<input type="text" class="col-md-12 btn-default form-control" id="start1" placeholder="Type your name" />
							<button type="button" id="startButton" class="col-md-12 btn btn-success" data-toggle="collapse" onclick="getName()" data-target="#demo"><i class="fa fa-comments" aria-hidden="true"></i> Start chat</button>
						</span>
					</div>
					<div>
						<br />
						<br />
						<br />
						<br />
						<h3>Welcome !</h3>
						<address>
							<strong> Our Public Chat Room</strong><br>
							We always appreciate you valuable feedbacky<br>
							We reccoment to type your name before start over conversation with us.<br>
							<br>

						</address>
					</div>
				</div>
				<div id="demo" class="navbar-fixed-bottom col-md-offset-8 col-md-4 collapse">
					<div>
						@Html.Partial("_chatView")
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB_LOYMhK-Q41Lz7QJjEvI3e-tiIsWaXRI&callback=myMap">
</script>
<script>
	var myCenter = new google.maps.LatLng(59.402986, 17.944129);
	var marker;

	//Create a function to initialize the map:

	function initialize()
		// create an object (mapProp) to define the properties for the map:
		//The center property specifies where to center the map. Create a LatLng object to center the map on a specific point. Pass the coordinates in the order: latitude, longitude.
		// The zoom property specifies the zoom level for the map. zoom: 0 shows a map of the Earth fully zoomed out. Higher zoom levels zoom in at a higher resolution.
	{
		var mapProp = {
			center: myCenter,
			zoom: 5,
			mapTypeId: google.maps.MapTypeId.ROADMAP
		};

		var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);

		var marker = new google.maps.Marker({
			position: myCenter,
			animation: google.maps.Animation.BOUNCE
		});

		marker.setMap(map);
	}

	//Create a div element to hold the map. Use CSS to size the element: after header

	//Add a DOM listener that will execute the initialize() function on window load (when the page is loaded):
	google.maps.event.addDomListener(window, 'load', initialize);
</script>

Ecomerce_Restaurant/Ecomerce_Restaurant/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h3>@ViewBag.Message</h3>
<div class="row">
    <div class="col-md-8">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="width:600px;height:400px" data-interval="3000">
            <!-- Indicators   //The indicators are the small radio buttons underneath the caption which are filled in when they’re active. The indicators are declared using an ordered list-->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>

            </ol>
            <!-- Wrapper for slides //contains the slider images and the captions-->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="~/Images/food_image_slide1.jpg" alt="..." style="width:100%;height:100%">
                    <div class="carousel-caption">
                        <h3>Caption Text</h3>
                    </div>
                </div>
                <div class="item">
                    <img src="~/Images/food_image_slide2.jpg" alt="..." style="width:100%;height:100%">
                    <div class="carousel-caption">
                        <h3>Caption Text</h3>
                    </div>
                </div>
            </div>
            <!-- Controls left and right arrows at the ends of the slider images-->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <div class="col-md-4">
        <h2>MAKE A RESERVATION!</h2>
        <p>I'm a Paragraph. Click here to add your own text and edit me. ​It’s easy. Just click “Edit Text” or double click me and you can start adding your own content...</p>
        <p>Click here to make a reservation online or <b>call us</b></p>
        <p><b>+4670000000</b></p>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Home")">Make a reservation &raquo;</a></p>
    </div>
</div>
<div class="row">
  
    <div class="col-md-6">
        <h2>Welcome</h2>
        <p>I'm a Paragraph. Click here to add your own text and edit me. It’s easy. Just click “Edit Text” I'm a Paragraph...</p>
        <p>I'm a Paragraph. Click here to add your own text and edit me. It’s easy. Just click “Edit Text” or double click me and you can start adding your own content...</p>
    </div>
    <div class="col-md-6">
        <h2>Lunch Special</h2>
        <p>We source the finest beers and wines and match them with your steak.</p>
        <p><a class="btn btn-default" href="@Url.Action("About", "Home")">READ MORE</a></p>
    </div>

</div>

<script>
    $('.carousel').carousel({
        interval: 3000
    })
</script>

Ecomerce_Restaurant/Ecomerce_Restaurant/Views/Home/SearchView.cshtml
@model IEnumerable<Ecomerce_Restaurant.Models.FoodModels.FoodName>

@{
    ViewBag.Title = "Search Result";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CategoryName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodDescription)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodPrice)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodRating)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TotalRatedPeople)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodItemPicName)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr class="warning">
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodDescription)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodRating)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalRatedPeople)
                        </td>
                        <td>
                            <img src="~/Images/@(item.FoodItemPicName)" height="50" width="50" />

                        </td>

                    </tr>
                }

            </table>
        </div>
    </div>
</div>

Ecomerce_Restaurant/Ecomerce_Restaurant/Views/Home/Store.cshtml
@model IEnumerable<Ecomerce_Restaurant.Models.FoodModels.FoodName>


<div class="panel panel-default">
    <div class="panel-heading">
        <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CategoryName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodDescription)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodPrice)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodRating)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.TotalRatedPeople)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FoodItemPicName)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr class="warning">
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CategoryName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodDescription)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodPrice)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FoodRating)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalRatedPeople)
                        </td>
                        <td>
                            <img src="~/Images/@(item.FoodItemPicName)" height="50" width="50" />

                        </td>
                        <td>
                            <p class="button">
                                @Html.ActionLink("Add to cart", "AddToCart","FoodNames", new { id = item.ID }, "")
                            </p>

                        </td>
                        @*<td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                            </td>*@
                    </tr>
                }

            </table>
        </div>
    </div>
</div>