Ecomerce_Restaurant/Ecomerce_Restaurant/Controllers/OrderController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Ecomerce_Restaurant.Models.FoodModels;

namespace Ecomerce_Restaurant.Controllers
{
	public class OrderController : Controller
	{
		private RestaurantContext db = new RestaurantContext();

		// GET: Order
		public ActionResult Index()
		{
			return View(db.Foods.ToList().OrderBy(x => x.CategoryName).ThenBy(x => x.FoodRating));
		}

		public ActionResult LunchFilter()
		{
			var x1 = db.Foods.Where(x => x.CategoryName == "Lunch").ToList();
			return View("Index",x1);
		}

		// GET: Order/Details/5
		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Food foodName = db.Foods.Find(id);
			if (foodName == null)
			{
				return HttpNotFound();
			}
			return View(foodName);
		}

		// GET: Order/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: Order/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "ID,Name,CategoryName,FoodDescription,FoodPrice,FoodRating,TotalRatedPeople,FoodItemPicName")] Food foodName)
		{
			if (ModelState.IsValid)
			{
				db.Foods.Add(foodName);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(foodName);
		}

		// GET: Order/Edit/5
		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Food foodName = db.Foods.Find(id);
			if (foodName == null)
			{
				return HttpNotFound();
			}
			return View(foodName);
		}

		// POST: Order/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "ID,Name,CategoryName,FoodDescription,FoodPrice,FoodRating,TotalRatedPeople,FoodItemPicName")] Food foodName)
		{
			if (ModelState.IsValid)
			{
				db.Entry(foodName).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(foodName);
		}

		// GET: Order/Delete/5
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Food foodName = db.Foods.Find(id);
			if (foodName == null)
			{
				return HttpNotFound();
			}
			return View(foodName);
		}

		// POST: Order/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			Food foodName = db.Foods.Find(id);
			db.Foods.Remove(foodName);
			db.SaveChanges();
			return RedirectToAction("Index");
		}


		[HttpPost]
		public ActionResult RateFood(int? rate, int foodId)
		{
			if (rate != null)
			{

				var food = db.Foods.Find(foodId);

				food.RatingCount++;

				food.FoodRating += rate.Value;

				//ViewBag.averageRating = food.FoodRating / food.RatingCount;

				db.Entry(food).State = EntityState.Modified;
				db.SaveChanges();
			}
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

Ecomerce_Restaurant/Ecomerce_Restaurant/Controllers/SuperadminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Ecomerce_Restaurant.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Ecomerce_Restaurant.Controllers
{
	public class SuperadminController : AccountController
	{
		// GET: Superadmin
		[Authorize(Roles = "SuperAdmin")]
		public ActionResult Index() 
		{
			var db = new ApplicationDbContext();
			//get users 
			List<ApplicationUser> users = db.Users.ToList();
			//----
			var roles = db.Roles.ToList();

			var userRolDictionary = new Dictionary<string, string>();
			foreach (var user in users)
			{
				var userRole = user.Roles.FirstOrDefault();
				if (userRole != null)
				{
					var userRoleId = userRole.RoleId;
					var roleName = roles.FirstOrDefault(x => x.Id == userRoleId);
					if (roleName != null) userRolDictionary.Add(user.UserName, roleName.Name);
				}
			}

			ViewBag.roles = new List<string>() { "General", "Admin" };
			return View(userRolDictionary);
		}


		[HttpPost]

		public async Task<ActionResult> updateRole(string userName, string new_role, string oldRole)
		{

			using (var db = new ApplicationDbContext())
			{
				var userid = db.Users.Where(x => x.UserName == userName).Select(x => x.Id).FirstOrDefault();

				if (!await RoleManager.RoleExistsAsync(new_role))
				{
					var identityrole = new IdentityRole
					{
						Id = Guid.NewGuid().ToString(),
						Name = new_role
					};
					await RoleManager.CreateAsync(identityrole);
				}
				await UserManager.RemoveFromRoleAsync(userid, oldRole);
				await UserManager.AddToRoleAsync(userid, new_role);
			}
			return RedirectToAction("Index","Home");
		}
	}
}

Ecomerce_Restaurant/Ecomerce_Restaurant/Views/Shared/_Footer.cshtml
<div class="container container-xs-height">
    <div class="row" id="my-footer-row">
        <div class="col-md-4 panel">
            <div class="well" style="background-color: #87ceeb">
                <h2>WHERE ARE WE?</h2><br />
				
				<a id="navLocation" class="btn btn-group-justified" href="@Url.Action("Contact", "Home")" role="button">Check our location</a>

	            @*Add text here<br />
                more text, more*@
            </div>
        </div>
        <div class="col-md-4 panel">
            <div class="well" style="background-color: #87ceeb">
                <p>
                    <h2>OPENING HOURS</h2><br>
                    We’re open everyday<br>
                    <h3>12:00pm-1:00am</h3>
                </p>
            </div>
        </div>
        <div class="col-md-4 panel">
            <div class="well" style="background-color: #87ceeb">
                <h2>CHEF AT HOME</h2>
                <address>
                    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
                    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
                </address>
            </div>
        </div>
    </div>
</div>

<p>&copy; @DateTime.Now.Year - IndianColor Restaurant Web Application</p>

Ecomerce_Restaurant/Ecomerce_Restaurant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title</title>

	@Scripts.Render("~/bundles/modernizr")

	<script src="~/Scripts/jquery-3.1.1.min.js"></script>
	<script src="~/Scripts/bootstrap.min.js"></script>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	@Styles.Render("~/Content/css")
	@Styles.Render("~/Content/bootstrap.min.css")
	@Styles.Render("~/Content/Site.css")

	<link href="~/Content/CustomCSS/RequiredField.css" rel="stylesheet" />
	<link href="~/Content/Site.css" rel="stylesheet" />
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<style>
		h1 {
			text-align: center;
		}

		#map-canvas {
			height: 500px;
		}
	</style>


	<script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>
	<script src="http://static.ak.connect.facebook.com/js/api_lib/v0.4/FeatureLoader.js.php" type="text/javascript"></script>
</head>

<body style="padding-top: 0px">

	<div class="jumbotron">
		<h1>Dhaka Food</h1>
	</div>

	<div class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" onclick="mobileView()">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>

			<div class="navbar-collapse collapse" id="customCollapse">
				<ul class="nav navbar-nav">
					<li><a id="navHome" class="btn btn-group-justified" href="@Url.Action("Index", "Home")" role="button"><i class="fa fa-home fa-2x col-lg-2" aria-hidden="true"></i></a></li>
					<li><a id="navLocation" class="btn btn-group-justified" href="@Url.Action("Contact", "Home")" role="button">Contact Us</a></li>
					<li>@Html.ActionLink("Menu", "Index", "Order")</li>

					@if (Request.IsAuthenticated && User.IsInRole("SuperAdmin"))
					{
						<li>@Html.ActionLink("Users", "Index", "Superadmin")</li>
					}

					@if (Request.IsAuthenticated && User.IsInRole("Admin"))
					{
						<li>@Html.ActionLink("Admin", "Index", "FoodCategories")</li>
					}

					@using (Html.BeginForm("SearchView", "Home"))
					{
						<form role="search" class="navbar-form navbar-left">
							<div class="form-group">
								<input type="text" name="searchvalue" placeholder="Search by category" class="form-control">
							</div>
						</form>
					}
				</ul>
				@Html.Partial("_LoginPartial")
			</div>
		</div>
	</div>

	<div class="container body-content">
		@RenderBody()
		<hr />
		<br />
		<br />
		<footer>
			@Html.Partial("_Footer")
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")

	@RenderSection("scripts", required: false)
	@RenderSection("chat", required: false)
	<script>
		var mobileView = function () {

			if (document.getElementById("customCollapse").style.display == "block") {
				document.getElementById("customCollapse").style.display = "none";
				console.log('hit-else');
			}
		};
	</script>
</body>
</html>

Ecomerce_Restaurant/Ecomerce_Restaurant/Views/Shared/_chatView.cshtml
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div class="panel panel-primary">
				<div class="panel-heading" id="accordion">
					<span class="glyphicon glyphicon-comment"></span> Chat
					<div class="btn-group pull-right">
						<a type="button" onclick="chatVisibility()" class="btn btn-default btn-xs">
							<span class="glyphicon glyphicon-chevron-down"></span>
						</a>
					</div>
				</div>
				<div class="panel-collapse collapse" id="collapseOne" style="display: block">
					<div class="panel-body">
						<ul class="chat">
							<li class="left clearfix">
								<div class="chat-body clearfix">
									<div class="col-xs-8">
										<input type="hidden" id="displayname" />
										<ul id="discussion"></ul>
									</div>
									@*<div class="col-xs-4">
										<ul class="text-muted" id="time"></ul> <br />
									</div>*@
								</div>
							</li>
						</ul>
					</div>
					<div class="panel-footer">
						<div class="input-group">
							<input id="message" type="text" class="form-control input-sm" placeholder="Type message" />
							<span class="input-group-btn">
								<ibutton class="btn btn-default" id="sendmessage" value="Send"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></ibutton>
							</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<script src="~/Scripts/CustomScript.js"></script>

<style>
	.chat {
		list-style: none;
		margin: 0;
		padding: 0;
	}

		.chat li {
			margin-bottom: 10px;
			padding-bottom: 5px;
			/*border-bottom: 1px dotted #B3A9A9;*/
		}

			.chat li.left .chat-body {
				margin-left: 0px;
			}

			.chat li.right .chat-body {
				margin-right: 5px;
			}


			.chat li .chat-body p {
				margin: 0;
				color: #777777;
			}

		.panel .slidedown .glyphicon, .chat .glyphicon {
			margin-right: 5px;
		}

	.panel-body {
		overflow-y: scroll;
		height: 230px;
	}

	::-webkit-scrollbar-track {
		-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
		background-color: #F5F5F5;
	}

	::-webkit-scrollbar {
		width: 12px;
		background-color: #F5F5F5;
	}

	::-webkit-scrollbar-thumb {
		-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,.3);
		background-color: #555;
	}
</style>